### PR TITLE
pep8 fix for Pilot3

### PR DESCRIPTION
**Pull request by hyoo**
this is all about white spacing, but wanted check with @gounley or @yngtodd

### CODE REVIEW

**Comment by jmohdyusof** [comment]
FWIW I would like to see some of the commented lines removed since they seem to be pretty static e.g. in Pilot3/P3B3/keras_mt_shared_cnn.py (which is inherited into the hackathon code)

**Comment by gounley** [comment]
I think it makes sense to delete https://github.com/hyoo/Benchmarks/blob/develop/Pilot3/P3B3/keras_mt_shared_cnn.py#L58, but I'm less bothered by the other comments

**Comment by hyoo** [comment]
how about now?

**Review by gounley — APPROVED** [review]
Looks good to me.

**Comment by jmohdyusof** [comment]
What about lines 36, 46? These lines in the middle of calls seem to hurt readability to me.

**Comment by hyoo** [comment]
To me, it looks okay. The comment implies that people tried the option and decided not to use it for some reason. At least, it reminds someone tried it.

**Comment by jmohdyusof** [comment]
I guess I am outvoted, so be it.

**Comment by yngtodd** [comment]
Are the commented lines [#L36](https://github.com/hyoo/Benchmarks/blob/develop/Pilot3/P3B3/keras_mt_shared_cnn.py#L36) and [#L46](https://github.com/hyoo/Benchmarks/blob/develop/Pilot3/P3B3/keras_mt_shared_cnn.py#L46) just using default parameters for that? I would say to remove those.

**Comment by hyoo** [comment]
it seems you commented when I merge it at the same time. Feel free to modify since the PR already merged.

**Comment by jmohdyusof** [comment]
It isn't obvious from this style what the default it (it could actually be the same as the commented out line) so I prefer to have the values set beforehand, so it is clear what it is.

**Pull request merged**
