### PR TITLE
[WIP] P3b7 - Model Pruning

### PR DESCRIPTION
**Pull request by yngtodd**
Adds a benchmark for pruning pytorch model weights.

### CODE REVIEW

**Comment by jmohdyusof** [comment]
I assume you now have permissions. It appears that optimize.py is actually p3b7_baseline_pytorch.py? It would be nice to make these consistent so users don't have to spend time figuring out which command line to run.

**Comment by jmohdyusof** [comment]
Also, please include something in the readme about what packages i need to make this work (pytorch pruning doesn't seem to be available?)

**Comment by yngtodd** [comment]
Sorry, just saw these comments. I can add that information for you.

**Comment by jmohdyusof** [comment]
I am finding several bugs in the code, including order of imports, missing params (KeyError: 'train_data') etc. Are these things it helps for me to fix or are they just because it is WIP?

**Comment by yngtodd** [comment]
Yeah, I am currently working on this. I went ahead and merged to the benchmarks branch so that we no longer need to keep the fork in sync.

**Comment by jmohdyusof** [comment]
OK, so this sounds like I shouldn't bother, or commit the fixes if they move the error to later in the code. What is the train_data file supposed to be, perhaps I can get the code to run.

**Comment by yngtodd** [comment]
This was a stand in for the P3 benchmark data that I have been using locally rather than connecting to the synthetic data that has been used for other P3 benchmarks. 

I will start cleaning this up and have in running shape soon

**Comment by jmohdyusof** [comment]
OK. FYI, it appears to require pytorch > 1.4.0 (to get prune) so that would be nice to add to the readme.

**Pull request merged**
