### PR TITLE
small bug fixes

### PR DESCRIPTION
**Pull request by hyoo**
1. replace inline class with candle function
2. plots are stored in args.save_path

### CODE REVIEW

**Comment by jmohdyusof** [comment]
So you are using both save_path and output_dir? Just checking..

**Comment by hyoo** [comment]
plot directory was hardcoded and now i am trying to use the user-provided location, which will be `args.save_path` I am not sure what `output_dir` is, but I guess that is for Supervisor

**Comment by jmohdyusof** [comment]
No, output_dir is the benchmark-level output directory (defaults to EXP000/RUN000) but is ignored by Supervisor. We talked at previous hackathons about using the same argument for both levels. output_dir is also automatically created by the candle utils if it doesn't exist (save_path is not).

**Comment by hyoo** [comment]
now, plots are saved in `output_dir`

**Comment by jmohdyusof** [comment]
OK, cool. We probably need to make this change a bunch of places since most of the benchmarks have similar issues.

**Pull request merged**
