### PR TITLE
Update adrp.py

### PR DESCRIPTION
**Pull request by rajeeja**
Removing subtraction, as not needed.

### CODE REVIEW

**Comment by rajeeja** [comment]
@jmohdyusof please review.

**Comment by jmohdyusof** [comment]
This seems fine, does it run without any keyword warnings now?

**Comment by jmohdyusof** [comment]
Before this merge, I get: RuntimeWarning: These keywords used in the configuration file are not defined in CANDLE: ['drop', 'in', 'nb_classes', 'solr_root', 'validation_split']

**Comment by rajeeja** [comment]
@jmohdyusof all fixed now. Thanks.

**Comment by rajeeja** [comment]
@jmohdyusof please review

**Comment by jmohdyusof** [comment]
validation_split should be val_split. It looks like you removed stuff, were they not being used at all?

**Comment by rajeeja** [comment]
Yes. They were not used. It was setting it to 0.1.
I think it can be dropped from default file for now

**Comment by jmohdyusof** [comment]
OK, will merge and test here.

**Comment by jmohdyusof** [comment]
Redefinition of metrics which are already defined in keras_utils.py. e.g. xent, mse, r2. Can you check these are the same or comment in the code that they are numerically different.

**Pull request merged**
