### PR TITLE
[WIP] P3B6

### PR DESCRIPTION
**Pull request by yngtodd**
Add BERT benchmark.

### CODE REVIEW

**Comment by jmohdyusof** [comment]
There are a ton of diffs to files in Pilot 1 and common. Can you make sure everything except the P3B6 files are current with the latest develop branch. I am not sure if there is a good way to just add files without updating existing.

**Comment by yngtodd** [comment]
Yeah, let me rebase that with the dev branch. I had originally branched off of the master branch.

**Comment by jmohdyusof** [comment]
Cool, thanks. I already had to fix some weird issues where people force pushed a bunch of out of date stuff.

**Comment by yngtodd** [comment]
Sorted out the conflicts. Next steps are to work with Justin on how to integrate `Horovod` into CANDLE's `Supervisor` bits.

**Comment by jmohdyusof** [comment]
OK. There are still some weird diffs that seem like leftovers from earlier commits in develop. FWIW, I know that some Benchmarks use Horovod so there should be working examples. If P3B6 is large and could scale it might be a good FlexFlow test case?

**Comment by gounley** [comment]
Yeah, if the dependencies aren't a problem, this would be a great FlexFlow test case.

**Comment by jmohdyusof** [comment]
OK, once it is merged to develop I will point the FlexFlow people at it. Big issue right now is this pull request appears to delete existing files in Pilot1/T29?

**Comment by yngtodd** [comment]
In an abundance of caution, I am going to close this PR in favor of another.

**Pull request closed without merging**
