### PR TITLE
First pass at making P1: Attn1 candle compliant

### PR DESCRIPTION
**Pull request by rajeeja**

### CODE REVIEW

**Comment by jmohdyusof** [comment]
It looks like you are replicating the builtin candle optimizer selection. This is already available from common/keras_utils, using the build_optimizer function.

**Comment by rajeeja** [comment]
> It looks like you are replicating the builtin candle optimizer selection. This is already available from common/keras_utils, using the build_optimizer function.

fixed.

**Comment by jmohdyusof** [comment]
Looks good. I will test it later today if you want, let me know if there is anything in particular I should take a look at.

**Comment by jmohdyusof** [comment]
Can you get the code to download the input file like the other benchmarks do?

**Comment by rajeeja** [comment]
I have updated the README with instructions to download:
wget http://ftp.mcs.anl.gov/pub/candle/public/benchmarks/Pilot1/uno/top_21_1fold_001.h5, since it is large, is it okay to have it in README and not autodownload?

**Comment by Tipizen** [comment]
It should auto download. Cache so it only downloads once.

**Comment by jmohdyusof** [comment]
The standard CANDLE get_file function will check for a local copy and only download if the local copy is not there. If it is a file from the Uno benchmark, then it is probably already present you just need to point to it, it should be in Data/Pilot1?

**Comment by jmohdyusof** [comment]
e.g. train_file = candle.get_file(file_train, url+file_train, cache_subdir='Pilot1')

**Comment by rajeeja** [comment]
autodownload works now.

**Comment by jmohdyusof** [comment]
Cool. If we merge can you continue to work on the develop branch?

**Comment by rajeeja** [comment]
Yes after merge, I can create a Supervisor workflow. I don't have access to commit to develop. For Benchmark, I can continue with my fork and do PR.

**Comment by jmohdyusof** [comment]
It looks like this works for tf<2? I am finding some issues with tf2 compatibility both in the library functions and the code itself, I will try to work through them.

**Pull request merged**
