### PR TITLE
pep8 fix for candle lib

### PR DESCRIPTION
**Pull request by hyoo**

### CODE REVIEW

**Comment by jmohdyusof** [comment]
Most of this looks fine, but there are some weird cases for long line continuation indentations that I am not sure of.

**Comment by hyoo** [comment]
would you point to one of those?

**Comment by jmohdyusof** [comment]
keras_utils line 32/34. Maybe it is the diff formatting that is confusing?

**Comment by hyoo** [comment]
yes, that is due to the diff display on the UI. This is from a text editor.

image

**Comment by jmohdyusof** [comment]
OK, this looks fine. I will approve once I am off this call.

**Comment by hyoo** [comment]
ah.. i accidentally committed to the ECP-CANDLE repo. I meant to add an extra commit to my fork and add them to the PR.

**Comment by jmohdyusof** [comment]
OK, I don't think we normally need pull requests for develop anyway.

**Comment by hyoo** [comment]
I just wanted to make sure you know the changes since those are on the candle libs. let me know anything that is not clear to you.

**Comment by jmohdyusof** [comment]
I appreciate it. Since there are no functional changes (and it still retains all the commented out stuff that we really need to clean up :) I am fine with this. Thanks for taking care of it.

**Pull request merged**
