### PR TITLE
Remove loguru

### PR DESCRIPTION
**Pull request by yngtodd**
We don't need to add this dependency just to print things.

### CODE REVIEW

**Comment by yngtodd** [comment]
@jmohdyusof I am going to double check that I caught all instances of `loguru`, but this PR should easily remove loguru as a dependency. It was just being used in the examples.

**Comment by jmohdyusof** [comment]
There are several other loggers available so it might be easier just to use one of them? Then the logger.info syntax can remain intact. e.g.
import logging
logger = logging.getLogger(__name__)
I will try this first.

**Comment by jmohdyusof** [comment]
Trying to run the uno example: Some keywords are not defined (some of these are close to CANDLE defaults, I can fix).
RuntimeWarning: These keywords used in the configuration file are not defined in CANDLE: ['grad_clip', 'learning_rate_min', 'log_interval', 'lr', 'lr_min', 'savepath', 'seed', 'unrolled', 'weight_decay']
Bigger problem:
Traceback (most recent call last):
  File "uno_example.py", line 196, in <module>
    main()
  File "uno_example.py", line 192, in main
    run(params)
  File "uno_example.py", line 96, in run
    device
  File "uno_example.py", line 137, in train
    unrolled=args.unrolled
  File "/home/jamal/Code/ECP/CANDLE/Benchmarks/common/darts/architecture.py", line 85, in step
    self.backward_step_unrolled(x_train, target_train, x_valid, target_valid, eta, optimizer)
  File "/home/jamal/Code/ECP/CANDLE/Benchmarks/common/darts/architecture.py", line 116, in backward_step_unrolled
    unrolled_model = self.comp_unrolled_model(x_train, target_train, eta, optimizer)
  File "/home/jamal/Code/ECP/CANDLE/Benchmarks/common/darts/architecture.py", line 58, in comp_unrolled_model
    dtheta = F.flatten(autograd.grad(loss, self.model.parameters())).data
  File "/home/jamal/.conda/envs/tf-gpu/lib/python3.6/site-packages/torch/autograd/__init__.py", line 150, in grad
    grad_outputs = _make_grads(outputs, grad_outputs)
  File "/home/jamal/.conda/envs/tf-gpu/lib/python3.6/site-packages/torch/autograd/__init__.py", line 32, in _make_grads
    if out.requires_grad:
AttributeError: 'dict' object has no attribute 'requires_grad'

**Comment by jmohdyusof** [comment]
default_model has learning_rate and lr both used (only learning_rate is a standard keyword). Ditto for lr_min, learning_rate_min

**Comment by yngtodd** [comment]
I suggest we remove the `unrolled` parameter. That is an additional approximation method in the algorithm, that requires some changes to the example and is not necessary.

**Comment by jmohdyusof** [comment]
Is this the same as setting unrolled = False in the default model file?

**Comment by jmohdyusof** [comment]
Setting unrolled=False seems to run? Hard to tell with no output:
(tf-gpu) [jamal@cn420 uno]$ python uno_example.py
Importing candle utils for pytorch
Params:
{'batch_size': 100,
 'data_type': <class 'numpy.float32'>,
 'data_url': 'http://ftp.mcs.anl.gov/pub/candle/public/benchmarks/Pilot1/uno/',
 'epochs': 10,
 'experiment_id': 'EXP000',
 'gpus': [],
 'grad_clip': 5,
 'learning_rate': 0.01,
 'learning_rate_min': 0.001,
 'log_interval': 10,
 'logfile': None,
 'model_name': 'darts_uno',
 'momentum': 0.9,
 'output_dir': '/home/jamal/Code/ECP/CANDLE/Benchmarks/examples/darts/uno/Output/EXP000/RUN000',
 'profiling': False,
 'rng_seed': 13,
 'run_id': 'RUN000',
 'save_path': '.',
 'shuffle': False,
 'timeout': -1,
 'train_bool': True,
 'train_data': 'top_21_auc_1fold.uno.h5',
 'unrolled': False,
 'verbose': None,
 'weight_decay': 0.0003}
================================================================================
Pytorch version: 1.3.1 cuda version 10.0.130 cudnn version 7605
CUDA Device name TITAN V
CUDA memory - total: 12066 current usage: 13
2020/05/07 - 09:53:23
================================================================================
/home/jamal/.conda/envs/tf-gpu/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)

**Comment by jmohdyusof** [comment]
This fixes the loguru issue:
#from loguru import logger
import logging
logging.basicConfig(level = logging.INFO)
logger = logging.getLogger(__name__)

**Comment by jmohdyusof** [comment]
I never pushed merged your original change anyway :)

**Comment by yngtodd** [comment]
I updated a couple of things for the Uno example: 

1. Fixed unrolled to be False - this is an unnecessary additional approximation for the algorithm. I could create another tutorial showing how to use that functionality later

2. Moved the learning rate scheduler so that `optimizer.step` is called before `scheduler.step`, eliminating that Pytorch warning.

**Comment by yngtodd** [comment]
The advanced example requires `torchvision` to get the data. How do we handle that dependency?

**Comment by jmohdyusof** [comment]
There is no explicit dependency list for CANDLE apart from in Tom's instructions for setup. I would suggest some changes to the readme's you have. 1) Move the darts explanation to the top-level (examples/darts) readme (the first section seems to be common in both uno and advances), and then include a note somewhere about additonal requirements. I am used to just installing extra packages via conda/pip as I go along, so I didn't notice. We are also going to add some packages to the top-level CANDLE install.

**Comment by yngtodd** [comment]
Cool, that sounds good to me. I will move that part of the README and will add a note about that dependency.

**Comment by jmohdyusof** [comment]
Can you check your default_model files. Both of them have both lr and learning_rate included (with lr_min and learning_rate_min). 'learning_rate' is the standard candle keyword. Values are different so you should make sure learning_rate is correct.

**Comment by jmohdyusof** [comment]
Minor stuff: I changed the log_interval to 100, and the pytorch install should probably mention pytorch-gpu since that makes a huge difference.

**Comment by yngtodd** [comment]
Right on, let me add that to the README.

**Comment by jmohdyusof** [comment]
Still some non-standard keyword usage: 
seed --> rng_seed (this is never used in the code, but will leave it for now?)
savepath --> save_path 

Suggested changes: 
log_interval: 10 --> 100 (manageable output size)
save_path: '.'-->'./results' (advanced has this already, uno needs fixing)
advanced/example.py --> advanced/advanced_example.py (matched uno_example.py)

**Comment by jmohdyusof** [comment]
Also, it looks like 
genotype_store = darts.GenotypeStorage(root=args.save_path)
can't handle creating a directory if it doesn't exist? 

Traceback (most recent call last):
  File "uno_example.py", line 199, in <module>
    main()
  File "uno_example.py", line 195, in main
    run(params)
  File "uno_example.py", line 96, in run
    device
  File "uno_example.py", line 158, in train
    genotype_store.save_genotype(genotype)
  File "/home/jamal/Code/ECP/CANDLE/Benchmarks/common/darts/storage/genotype.py", line 27, in save_genotype
    with open(path, 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: './results/genotype.json'

**Pull request merged**
