### PR TITLE
Enable support for Tensorflow 2.0 in NT3

### PR DESCRIPTION
**Pull request by mdorier**
This PR makes changes to enable the NT3 model `nt3_baseline_keras2.py` to be run with Tensorflow 2.0 (which ships with its own version of Keras). Most of the changes involve trying to import packages from keras and, if it fails, import the same packages from tensorflow.keras.

### CODE REVIEW

**Comment by jmohdyusof** [comment]
I cannot test the branch dev-tf2 because it doesn't appear to be in the repo?

**Comment by mdorier** [comment]
It's on my fork of the repo: https://github.com/mdorier/Benchmarks/tree/dev-tf2

**Comment by jmohdyusof** [comment]
I asked Justin to give you permissions to create a branch in our repo so we don't have to keep them separate.

**Comment by hyoo** [comment]
This has been addressed by the recent namespace migration to `tensorflow.keras`

**Pull request closed without merging**
