### PR TITLE
o Fix formatting to get pre-commits working

### PR DESCRIPTION
**Pull request by rajeeja**

### CODE REVIEW

**Comment by rajeeja** [comment]
@jmohdyusof

**Comment by jmohdyusof** [comment]
Don't you have permissions to commit directly to develop?

**Comment by rajeeja** [comment]
No.

**Comment by jmohdyusof** [comment]
Logs show you have committed to develop a bunch of times.

**Comment by rajeeja** [comment]
It has always been through pull requests from my fork

________________________________

**Review by jmohdyusof — APPROVED** [review]

**Pull request merged**
